defaultEntryPoints = ["http"]

[log]
  level = "DEBUG"
  format = "json"

[accessLog]
  [accessLog.fields]
    defaultMode = "keep"
    
    [accessLog.fields.headers]
      defaultMode = "keep"
# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"

[file]
[backends]
  [backends.django]
    [backends.django.servers.server1]
      url = "http://localhost:8080"

[frontends]
  [frontends.staging_healthcheck]
    backend = "django"
    passHostHeader = true
    [frontends.staging_healthcheck.headers]
      HostsProxyHeaders = ['X-CSRFToken']
    [frontends.staging_healthcheck.routes.health]
      rule = "PathPrefixStrip: /healthcheck"
  [frontends.staging]
    backend = "django"
    passHostHeader = true
    [frontends.staging.routes.host]
      rule = "Host:staging.mmpl.systemiphus.com"
    [frontends.staging.headers]
      HostsProxyHeaders = ['X-CSRFToken']
